erda-project/erda-infra

- .gitignore
What this PR does / why we need it:
- add macOS files
- add vim files
- add vscode files
Special notes for your reviewer:
/cc @luobily @skoo87
> update(gitignore): add some ignore files in git ignore

- providers/health/examples/examples.yaml
- providers/health/examples/main.go
- providers/health/provider.go
- providers/i18n/provider.go
- providers/legacy/httpendpoints/endpoints.go
- providers/legacy/httpendpoints/errorresp/error_codes.go
- providers/legacy/httpendpoints/errorresp/errors.go
- providers/legacy/httpendpoints/errorresp/response.go
- providers/legacy/httpendpoints/examples/examples.yaml
- providers/legacy/httpendpoints/examples/httpendpoints.yml
- providers/legacy/httpendpoints/examples/main.go
- providers/legacy/httpendpoints/i18n/locale_resource.go
- providers/legacy/httpendpoints/i18n/template.go
- providers/legacy/httpendpoints/ierror/ierror.go
- providers/legacy/httpendpoints/interface.go
- providers/legacy/httpendpoints/provider.go
- providers/legacy/httpendpoints/response.go
- providers/legacy/httpendpoints/response_test.go
1、optimize health provider.
2、i18n support get text with default value.
3、http-endpoints providers.
> health、i18n、http-endpoints providers

- .github/ISSUE_TEMPALTE/bug_report.md
- .github/ISSUE_TEMPALTE/feature.md
- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
feat(github): update github pr and issue template
/cc @luobily @liuhaoyang @Effet
> feat(github): update github pr and issue template

- OWNERS
feat(Owners): update owners file
Fixes #
/assgin
```release-note
```
```docs
```
> feat(Owners): update owners file

- .github/workflows/ci-it.yml
- .golangci.yml
- providers/kafka/consumer.go
- providers/legacy/httpendpoints/endpoints.go
- providers/legacy/httpendpoints/errorresp/errors.go
- providers/legacy/httpendpoints/ierror/ierror.go
- providers/pprof/examples/main.go
> Add ci and it workflow

- go.mod
- providers/kafka/consumer.go
- providers/kafka/examples/examples.yaml
- providers/kafka/examples/main.go
- providers/kafka/kafka.go
/kind bug
fix kafka provider、add example
```
```
@liuhaoyang 
```release-note
```
```docs
providers/kafka/examples/
```
> fix kafka provider、add example

- .github/workflows/ci-it.yml
- .golangci.yml
- README.md
> Add code coverage badge

- README.md
- README_zh.md
- base/servicehub/default_provider_define.go
- base/servicehub/examples/simple_define/examples.yaml
- base/servicehub/examples/simple_define/main.go
- base/servicehub/hub.go
- base/servicehub/hub_test.go
- base/servicehub/usage.go
- base/servicehub/usage_test.go
- providers/health/examples/main.go
- providers/httpserver/examples/examples.yaml
- providers/httpserver/examples/main.go
- providers/i18n/examples/main.go
- providers/kafka/examples/main.go
- providers/kubernetes/examples/main.go
/kind feature
simple way to define provider
@liuhaoyang 
```docs
base/servicehub/examples/simple_define/main.go 
```
> simple way to define provider

- README_zh.md
- examples/protocol/pb/greeter.http.pb.go
- examples/protocol/pb/user.http.pb.go
- tools/protoc-gen-go-http/service.go
- tools/protoc.sh
/kind bug
/kind feature
1、support custom pb output path
2、fix protoc-gen-go-http package import
@liuhaoyang
> support custom pb out path

- pkg/transport/http/default_handle.go
- pkg/transport/transport.go
/kind feature
expose http options
@liuhaoyang
> expose http options

- pkg/transport/http/compress/compress.go
- pkg/transport/http/compress/compress_test.go
supplement the CompressWithGzip under the pkg package of the erda-infra
What type of PR is this?
/kind feature
What this PR does / why we need it:
supplement the CompressWithGzip
Specified Reivewers:
/assgin @recallsong
> CompressWithGzip placed under the pkg package of the erda-infra repo.

- .github/workflows/license-check.yml
- .licenserc.json
> Add license-check action

- go.mod
/kind bug
invalid client-go version in go.mod, "go get" will not be able to use
errors like:
```shell
go: github.com/erda-project/erda-infra@v0.0.0-20210407072029-60083c06846f requires
k8s.io/client-go@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```
Fixes #
@recallsong 
```release-note
```
```docs
```
> fix client-go version

- .github/workflows/ci-it.yml
- go.mod
- tools/dockerfile/build.sh
- tools/go.mod
upgrade go version to 1.16, get the leverage of `go embed`.
Fixes #
@liuhaoyang 
```release-note
NONE
```
```docs
```
> upgrade go version to 1.16

- providers/etcd/etcd.go
/kind feature
dial block with timeout instead of running backgroud when bootstrap
Fixes #
@recallsong 
```release-note
```
```docs
```
> connection block at bootstrap

- .github/PULL_REQUEST_TEMPLATE.md
/kind cleanup
update PULL REUQEST TEMPLATE.md
/assgin @luobily
> update PULL REUQEST TEMPLATE.md

- pkg/transport/http/encoding/encoding.go
- pkg/transport/http/runtime/parser_test.go
- tools/protoc/protoc-gen-go-form/form.go
/kind bug
1、fix proto-gen-go-form、
2、http support application/vnd.*+json
@liuhaoyang
> fix proto-gen-go-form、http support application/vnd.x+json

- modcom/api/errors.go
- modcom/common.go
- providers/i18n/provider.go
- tools/protoc/protoc-gen-go-provider/provider.go
/kind feature
1、adjust proto-gen-go-provider
2、modcom support RegisterHubListener
3、add Internationalizable interface
@liuhaoyang
> adjust proto-gen-go-provider

- pkg/transport/grpc/grpc.go
- pkg/transport/http/handle.go
- pkg/transport/transport.go
- providers/i18n/provider.go
- tools/gohub/cmd/protoc/protoc.go
- tools/gohub/cmd/tools/install/install.go
/kind bug
/kind feature
1、support protobuf data validate
2、fix interceptor、i18n bug
3、get full method name from context
@liuhaoyang
> support protobuf data validate

- pkg/transport/http/encoding/encoding.go
- providers/i18n/examples/main.go
- providers/i18n/provider.go
/kind bug
1、fix i18n
2、fix http decoding
@liuhaoyang
> 1、fix i18n、fix http decoding

- modcom/api/model.go
- tools/gohub/cmd/protoc/protoc.go
/kind feature
1、protobuf include parameter
2、get body from *RawResponse
@liuhaoyang
> 1、protobuf include parameter

- go.mod
- pkg/transport/http/encoding/jsonpb/encode.go
- pkg/transport/http/encoding/jsonpb/json.go
- tools/protoc/protoc-gen-go-json/json.go
/kind feature
1、fix json marshal int64 
@liuhaoyang
> json marshaler

- pkg/transport/http/encoding/encoding.go
/kind bug
fix json unmarshal
@liuhaoyang
> fix json unmarshal

- .gitignore
- go.mod
- go.sum
- providers/mysqlxorm/examples/examples.yaml
- providers/mysqlxorm/examples/main.go
- providers/mysqlxorm/xorm.go
/kind feature
add new provider: mysqlxorm
> add new provider mysqlxorm

- examples/example/helloworld/provider.go
- providers/mysqlxorm/xorm.go
- tools/gohub/cmd/tools/install/install.go
- tools/gohub/cmd/version/version.go
- tools/protoc/protoc-gen-go-form/form.go
- tools/protoc/protoc-gen-go-http/service.go
/kind feature
1、support optional for protoc-gen-go-form
2、check version in gohub
@liuhaoyang
> support optional for protoc-gen-go-form、check version in gohub

- pkg/transport/transport.go
/kind feature
get grpc header from client directly
@liuhaoyang
> get grpc header from client directly

- go.mod
- pkg/math/math.go
- pkg/math/math_test.go
- providers/kafka/producer.go
/kind bug
/kind cleanup
/kind feature
/kind design
Fixes #
/assgin @your-reviewer
> Optimize Kafka producer

- pkg/strutil/interface.go
- pkg/strutil/interface_test.go
- pkg/strutil/namestyle.go
- pkg/strutil/namestyle_test.go
- pkg/strutil/regexp.go
- pkg/strutil/regexp_test.go
- pkg/strutil/strutil.go
- pkg/strutil/strutil_test.go
- pkg/strutil/validator.go
- pkg/strutil/validator_test.go
/kind feature
strutil pkg is better to be located in erda-infra.
erda-infra can use this pkg also.
> feature: move strutil pkg from erda to infra

- base/servicehub/examples/dependency-multi/main.go
- base/servicehub/hub.go
- go.mod
- go.sum
/kind feature
- update go version of go-utils [pr](https://github.com/recallsong/go-utils/pull/2)
- polish log when multi-instances provider init
> polish servicehub

- providers/cassandra/cassandra.go
- providers/cassandra/writer.go
/kind bug
/kind cleanup
/kind feature
/kind design
Fixes #
> writer with new session

- base/servicehub/provider.go
- base/servicehub/provider_context.go
- go.mod
- go.sum
- providers/component-protocol/examples/components/demotable/provider.go
- providers/component-protocol/examples/demo.yaml
- providers/component-protocol/protocol/component.go
- providers/component-protocol/provider.go
- providers/component-protocol/utils/cputil/sdk.go
/kind polish
- infra: enhance ProviderContext interface, expose `Key()` and `Provider()` to distinguish embed provider struct ![use-case](https://user-images.githubusercontent.com/13919034/131275177-ee246a2b-ba2c-48c1-9636-739843a7db0d.png)
- polish component-protcol provider
/assign @recallsong @Effet @liuhaoyang
> infra: enhance ProviderContext interface; polish component-protcol provider

- providers/httpserver/examples/reloadable/examples.yaml
- providers/httpserver/examples/reloadable/main.go
- providers/httpserver/provider.go
- providers/httpserver/router.go
- providers/httpserver/server/router.go
/kind bug
fix http server reloadable bug
> fix http server reloadable bug

- go.mod
- go.sum
- providers/component-protocol/protocol/register.go
- providers/remote-forward/client/examples/examples.yaml
- providers/remote-forward/client/examples/main.go
- providers/remote-forward/client/provider.go
- providers/remote-forward/connect.go
- providers/remote-forward/protocol.go
- providers/remote-forward/protocol_test.go
- providers/remote-forward/server/examples/examples.yaml
- providers/remote-forward/server/examples/main.go
- providers/remote-forward/server/provider.go
/kind feature
add provider, forward remote request to local
> forward remote request to local

- base/servicehub/config.go
- pkg/transport/http/encoding/encoding.go
- pkg/transport/http/encoding/encoding_test.go
/kind bug
/kind feature
1.http encode support bytes type 
2. fix dependency issue about module name
> http encode support bytes type & fix dependency issue

- providers/etcd-mutex/examples/main.go
- providers/etcd-mutex/mutex.go
> fix etcd mutex

- providers/i18n/examples/main.go
- providers/i18n/provider.go
/kind bug
fix i18n bug
/assign @johnlanni
> fix i18n bug

- providers/httpserver/router.go
- providers/httpserver/router_test.go
/kind feature
check path conflict ignore parameter name
> check path conflict ignore parameter name

- pkg/transport/http/handle.go
- providers/grpcclient/provider.go
> fix mismatch of interface and implementation of grpcclient

- providers/etcd-election/election.go
- providers/etcd-election/election_test.go
/kind feature
- add resign log
- unit-test remove temp data dir
/assign @hoozecn
> etcd-election add resign log & remove temp data dir

- base/servicehub/hub.go
feature
Add a log of provider initialization
Fixes #
> Add a log of provider initialization

- providers/component-protocol/provider.go
- providers/component-protocol/provider_test.go
/kind bug
add encoder to handle cp error
Fixes #
/assign @sfwn
> add error encoder

- providers/component-protocol/provider.go
/kind bug
add json header in cp encoder
> add json header in encoder

- providers/component-protocol/cptype/const.go
- providers/component-protocol/cptype/protocol.go
- providers/component-protocol/cptype/sdk.go
- providers/component-protocol/protocol.service.go
- providers/component-protocol/protocol/render.go
/kind feature
support temp state & InParams helper
Fixes #
/assign @sfwn
> support temp state & InParams helper

- providers/component-protocol/protocol/render.go
- providers/component-protocol/protocol/render_test.go
/kind feature
support footer in structure
Fixes #
/assign @sfwn
> support footer in structure

- providers/mysql/examples/examples.yaml
- providers/mysql/examples/main.go
- providers/mysql/mysql.go
/kind feature
mysql-provider support debug mode
> feature: mysql-provider support debug mode

- providers/prometheus/examples/examples.yaml
- providers/prometheus/provider.go
/kind bug
/kind cleanup
/kind feature
/kind design
prometheus router configurable
Fixes #
> router configurable

- providers/mysql/examples/examples.yaml
- providers/mysql/mysql.go
/kind enhancement
fix: typo in mysql-provider
> fix: typo in mysql-provider

- providers/component-protocol/protocol/render.go
- providers/component-protocol/protocol/render_test.go
/kind bug
fix calculate children hierarchy
Fixes #
> fix calculate children hierarchy

- providers/component-protocol/cptype/protocol.go
/kind bug
cp: add yaml tag for protocol options
/assign @Effet
> cp: add yaml tag for protocol options

- tools/protoc/protoc-gen-go-client/client.go
- tools/protoc/protoc-gen-go-client/provider.go
/kind bug
- for stream api, the generated method of Server interface is wrong
- expose xxx.client services in provider
/assign @liuhaoyang @recallsong
> bugfix: fix stream api generated error

- tools/gohub/cmd/version/version.go
> feature: udpate gohub version

- pkg/trace/inject/http-client/http_client.go
/kind feature
hook transport roundtrip
> hook transport roundtrip

- providers/component-protocol/components/kanban/impl/default.go
- providers/component-protocol/cptype/operation.go
- providers/component-protocol/cptype/sdk.go
- providers/component-protocol/examples/scenarios/kanban-demo.yml
- providers/component-protocol/protocol/framework.go
- providers/component-protocol/protocol/render.go
/kind feature
cp: remove useless UniversalStructuredCompPtr
/assign @Effet
> cp: remove useless UniversalStructuredCompPtr

- providers/component-protocol/components/filter/custom.go
- providers/component-protocol/components/filter/impl/decoder.go
- providers/component-protocol/components/filter/impl/default.go
- providers/component-protocol/components/filter/impl/encoder.go
- providers/component-protocol/components/filter/interface.go
- providers/component-protocol/components/filter/model.go
- providers/component-protocol/components/filter/models/condition.go
- providers/component-protocol/components/filter/models/option.go
- providers/component-protocol/components/filter/operation.go
- providers/component-protocol/examples/components/filter_demo/filter/init.go
- providers/component-protocol/examples/components/filter_demo/filter/provider.go
- providers/component-protocol/examples/demo.yaml
- providers/component-protocol/examples/scenarios/filter-demo.yml
- providers/component-protocol/protocol/render.go
> Component standard configurable filter set up

- providers/component-protocol/components/kanban/impl/default.go
/kind feature
cp: defaultKanban implement visible default to true
/assign @Effet
> cp: defaultKanban implement visible default to true

- providers/component-protocol/components/filter/custom.go
- providers/component-protocol/components/filter/impl/decoder.go
- providers/component-protocol/components/filter/impl/default.go
- providers/component-protocol/components/filter/impl/encoder.go
- providers/component-protocol/components/filter/model.go
- providers/component-protocol/components/filter/models/condition.go
- providers/component-protocol/components/filter/models/option.go
- providers/component-protocol/examples/components/filter_demo/filter/provider.go
/kind bug
/kind cleanup
/kind feature
/kind design
Fixes #
> Update component configurable filter model

- providers/component-protocol/components/topn/model.go
/kind bug
/kind cleanup
/kind feature
/kind design
Fixes #
> topn percent

- providers/component-protocol/components/filter/impl/default.go
- providers/component-protocol/components/kanban/impl/default.go
- providers/component-protocol/components/topn/impl/default.go
- providers/component-protocol/cptype/component.go
- providers/component-protocol/cptype/component_default.go
- providers/component-protocol/examples/components/kanban_demo/kanban/provider.go
- providers/component-protocol/protocol/framework.go
/kind feature
feature: cp comp instance support register non-std operations
[Erda Issue Link](https://erda.cloud/erda/dop/projects/387/issues/task?id=267359&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDA2LDQ0MDddfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=TASK)
/assign @Effet @WeiXuSeu
> feature: cp comp instance support register non-std operations

- providers/component-protocol/components/list/custom.go
- providers/component-protocol/components/list/impl/decoder.go
- providers/component-protocol/components/list/impl/default.go
- providers/component-protocol/components/list/impl/encoder.go
- providers/component-protocol/components/list/interface.go
- providers/component-protocol/components/list/model.go
- providers/component-protocol/components/list/model_test.go
- providers/component-protocol/components/list/operation.go
/kind feature
add basic list component
Fixes #
/assign @sfwn
> cp: add basic list component

- providers/component-protocol/components/cardlist/custom.go
- providers/component-protocol/components/cardlist/impl/decoder.go
- providers/component-protocol/components/cardlist/impl/default.go
- providers/component-protocol/components/cardlist/impl/encoder.go
- providers/component-protocol/components/cardlist/interface.go
- providers/component-protocol/components/cardlist/model.go
- providers/component-protocol/components/cardlist/models/textInfo.go
- providers/component-protocol/components/cardlist/operation.go
/kind feature
Fixes #
/assign @sfwn
> feat(component-protocol): add component cardlist

- providers/component-protocol/components/cardlist/impl/default.go
- providers/component-protocol/components/cardlist/interface.go
- providers/component-protocol/components/cardlist/model.go
- providers/component-protocol/components/cardlist/models/textInfo.go
- providers/component-protocol/components/cardlist/operation.go
/kind refactor
change fields and add star operation
Fixes #
/assign @sfwn
> refactor(cp): change fields and add star operation

- providers/component-protocol/components/cardlist/model.go
- providers/component-protocol/components/cardlist/models/textInfo.go
> refactor(cp): change textinfo to textmeta

- providers/component-protocol/components/list/impl/default.go
- providers/component-protocol/components/list/interface.go
- providers/component-protocol/components/list/model.go
- providers/component-protocol/components/list/operation.go
/kind feature
add std operations
Fixes #
/assign @sfwn
> add std operations

- providers/component-protocol/components/cardlist/impl/default.go
- providers/component-protocol/components/cardlist/interface.go
- providers/component-protocol/components/cardlist/model.go
- providers/component-protocol/components/cardlist/operation.go
/kind bug
/kind cleanup
/kind feature
/kind design
Fixes #
> refactor(cp): card list

- providers/component-protocol/components/cardlist/model.go
- providers/component-protocol/cptype/operation.go
- providers/component-protocol/utils/cputil/operation_builder.go
/kind bug
Fixes #
/assign @sfwn 
add tip field to operation
> add tip field to operation

- providers/component-protocol/components/list/operation.go
/kind bug
message list, need client data when click
Fixes #
/assign
> message list, need client data when click

- providers/component-protocol/components/list/model.go
/kind bug
update list star to point
Fixes #
/assign @sfwn
> update list star to point

- pkg/trace/inject/context/context.go
/kind bug
func-routine.goid don't support arm system
Fixes #
> fix arm system panic

- providers/component-protocol/components/cardlist/model.go
> refactor(cp): remove cards json tag

- providers/component-protocol/components/list/model.go
/kind bug
set main state to point
Fixes #
/assign @sfwn
> set main state to point

- providers/component-protocol/components/commodel/color.go
- providers/component-protocol/components/commodel/dropdownmenu.go
- providers/component-protocol/components/commodel/status.go
- providers/component-protocol/components/commodel/text.go
- providers/component-protocol/components/commodel/userselector.go
- providers/component-protocol/components/table/cell_builder.go
- providers/component-protocol/components/table/impl/decoder.go
- providers/component-protocol/components/table/impl/default.go
- providers/component-protocol/components/table/impl/encoder.go
- providers/component-protocol/components/table/interface.go
- providers/component-protocol/components/table/model.go
- providers/component-protocol/components/table/operation.go
- providers/component-protocol/examples/components/all.go
- providers/component-protocol/examples/components/table_demo/table/init.go
- providers/component-protocol/examples/components/table_demo/table/provider.go
- providers/component-protocol/examples/demo.yaml
- providers/component-protocol/examples/scenarios/table-demo.yml
/kind feature
component-procotol: add std table
/assign @Effet
> cp: add std table

- providers/component-protocol/components/linegraph/impl/decoder.go
- providers/component-protocol/components/linegraph/impl/default.go
- providers/component-protocol/components/linegraph/impl/encoder.go
- providers/component-protocol/components/linegraph/interface.go
- providers/component-protocol/components/linegraph/model.go
- providers/component-protocol/examples/components/all.go
- providers/component-protocol/examples/components/linegraph_demo/linegraph/provider.go
- providers/component-protocol/examples/demo.yaml
- providers/component-protocol/examples/scenarios/linegraph-demo.yml
> feature: support line graph

- providers/component-protocol/protocol/framework.go
/kind bugfix
cp: fix component unmarshal omitempty issue
/assign @Effet
> cp: fix component unmarshal omitempty issue

- providers/component-protocol/components/linegraph/model.go
- providers/component-protocol/examples/components/linegraph_demo/linegraph/provider.go
> feature: linegraph init

- .github/semantic.yml
add semantic.yml for pr title check
Fixes #
/assign @sfwn
> chore: add semantic.yml for pr title check

- .github/PULL_REQUEST_TEMPLATE.md
remove useless type of pr template
Fixes #
/assign @sfwn
> chore: remove useless type of pr template

- providers/component-protocol/components/kv/custom.go
- providers/component-protocol/components/kv/impl/decoder.go
- providers/component-protocol/components/kv/impl/encoder.go
- providers/component-protocol/components/linegraph/custom.go
- providers/component-protocol/components/linegraph/impl/decoder.go
- providers/component-protocol/components/linegraph/impl/encoder.go
- providers/component-protocol/components/topn/custom.go
- providers/component-protocol/components/topn/impl/decoder.go
- providers/component-protocol/components/topn/impl/encoder.go
defined customData for kv,topn,linegraph components
> feat: defined customData for kv,topn,linegraph components

- .gitignore
- providers/component-protocol/components/filter/models/option.go
- providers/component-protocol/examples/components/filter_demo/filter/provider.go
> feat: Add fix property in filter option base

- providers/component-protocol/components/table/model.go
> feat: add sorter field for Table

- providers/component-protocol/components/table/operation.go
table operation : pageNo pageSize
> fix: fix table operation 

- providers/component-protocol/components/bubblegraph/custom.go
- providers/component-protocol/components/bubblegraph/impl/decoder.go
- providers/component-protocol/components/bubblegraph/impl/default.go
- providers/component-protocol/components/bubblegraph/impl/encoder.go
- providers/component-protocol/components/bubblegraph/interface.go
- providers/component-protocol/components/bubblegraph/model.go
- providers/component-protocol/examples/components/all.go
- providers/component-protocol/examples/components/bubblegraph_demo/bubblegraph/provider.go
- providers/component-protocol/examples/demo.yaml
- providers/component-protocol/examples/scenarios/bubblegraph-demo.yml
bubble graph component ready to go
> feat: bubble graph component

- providers/component-protocol/examples/components/kanban_demo/kanban/custom_type.go
- providers/component-protocol/examples/components/kanban_demo/kanban/provider.go
add demo usage for cp custom type
/assign @Effet
> feat: add demo usage for cp custom type

- providers/component-protocol/protocol/render_parallel.go
> fix: parallel rending bugfix, ignore non exist component when do custom rending

- providers/component-protocol/components/list/impl/default.go
- providers/component-protocol/components/list/interface.go
- providers/component-protocol/components/list/model.go
- providers/component-protocol/components/list/operation.go
- providers/component-protocol/cptype/operation.go
> refactor(cp): change list

- providers/component-protocol/components/list/model.go
> refactor(cp): delete key for moreOp in component list

- providers/component-protocol/components/commodel/click.go
- providers/component-protocol/components/commodel/moreoperations.go
- providers/component-protocol/components/table/cell_builder.go
- providers/component-protocol/examples/components/table_demo/table/provider.go
cp: table support moreOperations
[Erda Related Issue](https://erda.cloud/erda/dop/projects/387/issues/all?id=274556&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=TASK)
/assign @Effet
> feat: cp: table support moreOperations

- providers/component-protocol/components/commodel/moreoperations.go
- providers/component-protocol/examples/components/table_demo/table/provider.go
table click add missing serverData&clientData
/assign @Effet
> feat: table click add missing serverData&clientData

- providers/component-protocol/components/commodel/text.go
- providers/component-protocol/components/filter/model.go
feat: support hide save filter & add status to text
Fixes #
/assign @sfwn
> feat: support hide save filter & add status to text

- providers/component-protocol/components/commodel/status.go
fix: update the status type of text model
Fixes #
/assign @sfwn
> fix: update the status type of text model

- providers/component-protocol/components/table/cell_builder.go
fix: fix the bug of user cell
Fixes #
/assign @sfwn
> fix: fix the bug of user cell

- providers/component-protocol/components/table/model.go
feat: table column support hidden
Fixes #
/assign @Effet
> feat: table column support hidden

- providers/component-protocol/components/filter/models/condition.go
feat: add disabled to filter condition
Fixes #
/assign @sfwn
> feat: add disabled to filter condition

- providers/component-protocol/cpregister/base/comp_register.go
fix: fix the nil pointer problem with base init
Fixes #
/assign @sfwn
> fix: fix the nil pointer problem with base init

- providers/component-protocol/components/defaults/default.go
fix: compatible with old register methods
Fixes #
/assign @Effet
> fix: compatible with old register methods

- providers/component-protocol/components/cardlist/impl/default.go
- providers/component-protocol/components/defaults/default.go
- providers/component-protocol/components/filter/impl/default.go
- providers/component-protocol/components/kanban/impl/default.go
- providers/component-protocol/components/list/impl/default.go
- providers/component-protocol/components/table/impl/default.go
- providers/component-protocol/cptype/component.go
- providers/component-protocol/cptype/operation.go
- providers/component-protocol/cptype/sdk.go
- providers/component-protocol/examples/components/bubblegraph_demo/bubblegraph/provider.go
- providers/component-protocol/examples/components/filter_demo/filter/provider.go
- providers/component-protocol/examples/components/kanban_demo/kanban/provider.go
- providers/component-protocol/examples/components/kv_demo/kv/provider.go
- providers/component-protocol/examples/components/linegraph_demo/linegraph/provider.go
- providers/component-protocol/examples/components/paralleldemo/comp.go
- providers/component-protocol/examples/components/table_demo/table/provider.go
- providers/component-protocol/examples/components/top_demo/top/provider.go
- providers/component-protocol/protocol/framework.go
cp: let EnhancedOperationFunc become OperationFunc
[Erda Issue](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODMsODgxLDc3Ml0sIm1lbWJlciI6WyI5MiJdfQ%3D%3D&id=275890&iterationID=772&pId=0&type=TASK)
/assign @Effet
> refactor: cp: let EnhancedOperationFunc become OperationFunc

- providers/component-protocol/components/list/model.go
> fix(cp): change selectable to pointer

- providers/component-protocol/components/list/model.go
> refactor(cp): change logourl to icon

- providers/component-protocol/components/commodel/duration.go
- providers/component-protocol/components/table/cell_builder.go
feat: add duration cellType
Fixes #
/assign @sfwn
> feat: add duration cellType

- providers/component-protocol/components/commodel/duration.go
- providers/component-protocol/components/table/cell_builder.go
fix: fix the bug of icon cell
Fixes #
/assign @sfwn
> fix: fix the bug of icon cell

- providers/component-protocol/components/commodel/progress.go
- providers/component-protocol/components/commodel/progress_bar.go
- providers/component-protocol/components/table/cell_builder.go
- providers/component-protocol/examples/components/table_demo/table/provider.go
feature: cp table add progressBar cellType
[Erda Issue](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODMsODgxLDc3Ml0sIm1lbWJlciI6WyI5MiJdfQ%3D%3D&id=277926&iterationID=772&pId=0&type=TASK)
/assign @Effet
> feat: cp table add progressBar cellType

- providers/component-protocol/cptype/protocol.go
cp global options add EnableWebSocket switch (default: false)
[Erda Issue](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODMsNzcyXSwibWVtYmVyIjpbIjkyIl19&id=275262&iterationID=772&pId=263525&type=TASK)
/assign @Effet
> feat: cp global options add EnableWebSocket switch (default: false)

- go.mod
- go.sum
- providers/component-protocol/cpregister/register_comp_provider.go
- providers/component-protocol/cpregister/register_comp_provider_test.go
- providers/component-protocol/cptype/sdk.go
- providers/component-protocol/cptype/sdk_test.go
- providers/component-protocol/protocol/framework.go
fix: cp sdk clone inParams&globalStates
/assign @Effet
> fix: cp sdk clone inParams&globalStates

- providers/component-protocol/examples/components/paralleldemo/comp.go
- providers/component-protocol/examples/components/paralleldemo/test.http
- providers/component-protocol/protocol/render.go
add missing posthook for parallel rendering
/assign @Effet
> fix: cp render posthook for parallel

- providers/component-protocol/cptype/websocket.go
add WebSocketEventType
[Erda Issue](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODMsNzcyXSwibWVtYmVyIjpbIjkyIl19&id=275266&iterationID=772&pId=263525&type=TASK)
/assign @Effet
> feat(component-protocol): add WebSocketEventType

- providers/component-protocol/protocol/framework.go
Component protocol set visible after operation handle
Fixes #
/assign @sfwn
> feat: Component protocol set visible after operation handle

- pkg/parallel/future.go
- pkg/parallel/future_test.go
- pkg/parallel/group.go
- pkg/parallel/group_test.go
- pkg/trace/trace.go
> feat: support traced go routine

- providers/component-protocol/protocol/render.go
> fix:Fix simplify comp default visible option

- providers/component-protocol/protocol/framework.go
> fix: Merge component global state after finalize

- providers/mysql/examples/examples.yaml
- providers/mysql/mysql.go
> fix: Add mysql charset client config

- providers/component-protocol/cptype/protocol.go
- providers/component-protocol/protocol/render.go
fix: cp: add ReturnAllComponents options
Fixes #
/assign @sfwn
> fix: cp: add ReturnAllComponents options

- pkg/parallel/future.go
- pkg/trace/trace.go
> fix: trace go run

- providers/component-protocol/protocol/scenario.go
fix: add Custom type comp
Fixes #
/assign @sfwn
> fix: add Custom type comp

- providers/component-protocol/cptype/protocol.go
- providers/component-protocol/examples/components/all.go
- providers/component-protocol/examples/components/filter_demo/filter/provider.go
- providers/component-protocol/examples/components/urlquery_demo/filter.go
- providers/component-protocol/examples/components/urlquery_demo/filter/filter.go
- providers/component-protocol/examples/scenarios/urlquery-demo.yml
- providers/component-protocol/protocol/posthook/simplify.go
- providers/component-protocol/protocol/posthook/urlquery.go
- providers/component-protocol/protocol/render.go
- providers/component-protocol/utils/cputil/urlquery.go
- providers/component-protocol/utils/cputil/urlquery_test.go
cp support urlQuery at protocol-level
[Related Erda Issue](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOlsxMDY5LDEwOTAsODgzLDc3Ml0sIm1lbWJlciI6WyI5MiJdfQ%3D%3D&id=265760&iterationID=1090&pId=0&type=TASK)
/assign @Effet
> feat: cp support urlQuery at protocol-level

- providers/component-protocol/components/list/operation.go
> refactor(cp-list): change list serverData from string to struct

- providers/etcd-election/election.go
etcd-election support NonVoter
/assign @sfwn
> feat: etcd-election support NonVoter

- providers/component-protocol/examples/scenarios/filter-demo.yml
- providers/component-protocol/protocol/posthook/continue_render.go
- providers/component-protocol/protocol/protocol.go
Get component from default protocol if not exist
Fixes #
/assign @sfwn
> feat: Get component from default protocol if not exist

- providers/component-protocol/protocol/render.go
- providers/component-protocol/protocol/render_test.go
slot rendering order takes precedence
Fixes #
> feat(component-protocol): slot rendering order takes precedence

- providers/mysql/examples/examples.yaml
- providers/mysql/mysql.go
> feature: mysql client support tls setting

- go.mod
- go.sum
- pkg/mysqldriver/tls.go
- pkg/mysqldriver/tls_test.go
- providers/mysql/mysql.go
- providers/mysql/mysql_test.go
- providers/mysql/v2/mysql.go
- providers/mysqlxorm/xorm.go
- providers/mysqlxorm/xorm_test.go
Database connection increases tls configuration
> feat: Database connection increases tls configuration

- base/servicehub/examples/dependency-autowired/examples.yaml
- base/servicehub/examples/dependency-autowired/main.go
- base/servicehub/hub.go
- base/servicehub/provider_context.go
> feat: autowired support inherit-label

- base/servicehub/hub.go
servicehub print signal when quit
/assign @Effet
> feat: servicehub print signal when quit

- pkg/safe/goroutine.go
- pkg/safe/goroutine_test.go
add safe pkg to recover from goroutine panic
/assign @Effet
> feat: add safe pkg to recover from goroutine panic

- providers/mysql/v2/mysql.go
same with #261 
/assign @Effet
> chore: enlarge mysql max open/idle connections for v2

- base/servicehub/config.go
- base/servicehub/hub.go
- base/servicehub/provider_context.go
- go.mod
- pkg/config/config.go
- pkg/config/config_test.go
- providers/component-protocol/protocol/translator/translator.go
- providers/i18n/provider.go
> feat: config support "|" operator

- pkg/safe/goroutine.go
add dump stack for safe pkg
/assign @Effet
> feat: add dump stack for safe pkg

- providers/cassandra/cassandra.go
- providers/cassandra/writer.go
support batch size bytes limit
Fixes #
> feat: support batch size bytes limit

- providers/i18n/examples/i18n/common/hello.yaml
- providers/i18n/examples/i18n/files/hello.yaml
- providers/i18n/examples/main.go
- providers/i18n/provider.go
- providers/i18n/register.go
- providers/i18n/register_test.go
add RegisterTextFromFS function to i18 provider
Fixes #
> feat: add RegisterTextFromFS function to i18 provider

- providers/i18n/register.go
fix: use file data register i18n file to provider
Fixes #
> fix: use file data register i18n file to provider

- providers/clickhouse/clickhouse.go
- providers/clickhouse/examples/examples.yaml
> feat: support readable config for ck

- tools/gohub/cmd/tools/install/install.go
- tools/gohub/cmd/version/version.go
update download link of protoc
/assign @snakorse
> chore: update download link of protoc

- tools/gohub/cmd/tools/install/install.go
> polish: git clone set depth to 1

- tools/gohub/cmd/tools/install/cmd.go
- tools/gohub/cmd/tools/install/install.go
add ghproxy&goproxy for gohub tools install
> feature: add ghproxy&goproxy for gohub tools install

- tools/dockerfile/build.sh
use buildx to build multi-arch gohub images simultaneously
> chore: use buildx to build multi-arch gohub images

- .gitignore
- tools/dockerfile/Dockerfile
- tools/gohub/cmd/protoc/protoc.go
- tools/gohub/cmd/tools/install/install.go
- tools/gohub/cmd/version/version.go
Use protoc-gen-validate as gohub validator tool
Fixes #
/assign @sfwn
> feat: Use protoc-gen-validate as gohub validator tool.

- providers/httpserver/interceptors/bodydump.go
- providers/httpserver/interceptors/log.go
- providers/httpserver/interceptors/requestid.go
- providers/httpserver/provider.go
- providers/httpserver/server/server.go
add useful middlewares for httpserver
> feat: add useful middlewares for httpserver

- providers/httpserver/examples/simple/examples.yaml
- providers/httpserver/interceptors/bodydump.go
- providers/httpserver/interceptors/cors.go
- providers/httpserver/interceptors/interceptor.go
- providers/httpserver/interceptors/interceptor_test.go
- providers/httpserver/interceptors/log.go
- providers/httpserver/interceptors/recover.go
- providers/httpserver/interceptors/requestid.go
- providers/httpserver/provider.go
enhance httpserver middlewares
> feat(httpserver): enhance middlewares

- providers/httpserver/path.go
- providers/httpserver/path_test.go
add path vars to request context
Fixes #
/assign @sfwn
> feat: add path vars to request context

- providers/mysql/v2/plugins/fields/soft_delete_stamp_test.go
- providers/mysql/v2/plugins/fields/soft_delete_test.go
- providers/mysql/v2/plugins/fields/uuid_test.go
- providers/mysql/v2/tx_test.go
comment out mysql v2 problematic unit tests temporarily
/assign @dspo
> chore: comment out mysql v2 problematic unit tests temporarily

- base/servicehub/hub.go
- base/servicehub/hub_test.go
hub print problematic providers for debug
> feat(hub): hub print problematic providers for debug

- providers/httpserver/provider.go
- providers/httpserver/router.go
- providers/httpserver/router_test.go
http-server router-manager support judge started
/assign @chengjoey
> feat: http-server router-manager support judge started

- providers/redis/redis.go
redis client maybe nil
/assign @shuofan
> fix: redis client maybe nil

- go.mod
- go.sum
- pkg/trace/inject/http-server/http_server.go
- tools/go.mod
support golang 1.19
/assign @sfwn
> chore: support golang 1.19

- providers/clickhouse/clickhouse.go
> [clickhouse] spell fix

- base/logs/logrusx/log.go
- base/logs/logs.go
add method `SetOutput` in `erda-infra.Logger`
Fixes #
/assign @sfwn
> fix: add logs methods

- .github/workflows/ci-it.yml
- pkg/trace/inject/hook/hook.go
- pkg/trace/inject/http-server/http_server.go
- pkg/trace/inject/http-server/http_server_test.go
gohook trampoline: make more room for a shadow copy of the original function
[Erda Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=549269&iterationID=12783&type=BUG)
> gohook trampoline: make more room for a shadow copy of the original function

- providers/grpcserver/provider.go
support set grpc server config by env
/assign @sfwn
> feat: support set grpc server config by env

- providers/grpcclient/provider.go
support set grpc client config by env
/assign @sfwn
> feat: support set grpc client config by env
