tools/gohub/cmd/tools/install/install.go
/kind bug
under mac M1, runtime.GOARCH value is arm64. because currently there is no real protobuf release for darwin-arm64 and the darwin-x64 binary can run on mac M1 with the rosetta compatibility, so here just use the same release.
/assgin @liuhaoyang  @recallsong
=> support mac M1

pkg/transport/http/encoding/encoding.go
/kind bug
https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.1
If no Accept header field is present, then it is assumed that the client accepts all media types. If an Accept header field is present, and if the server cannot send a response which is acceptable according to the combined Accept field value, then the server SHOULD send a 406 (not acceptable) response.
@liuhaoyang
=> fix accept

providers/mysqlxorm/examples/examples.yaml, providers/mysqlxorm/examples/main.go, providers/mysqlxorm/session.go, providers/mysqlxorm/xorm.go
/kind feature
- support ping when init to check database advanced
- migrated feature: support session for transparent transaction delivery, see example for usage, which is already used in pipeline
=> provider mysqlxorm support session for transparent transaction and init-ping

providers/mysqlxorm/xorm.go
/kind feature
Support custom properties for mysqlxorm.
Default is `charset=utf8mb4&collation=utf8mb4_unicode_ci&parseTime=True&loc=Local`
=> mysqlxorm support custom properties

go.mod, go.sum
/kind bug
In order to avoid 'gocql: no hosts available in the pool ' beacuse of reconnection issue
(https://github.com/gocql/gocql/issues/915)
Upgrade to fix it
(https://github.com/gocql/gocql/pull/1555)
Fixes #
/assgin @your-reviewer
=> upgrade gocql to fix reconnection

.github/PULL_REQUEST_TEMPLATE.md
/kind polish
Fix typo of `assign`. So erda-bot can assign pr reviewers correctly.
=> fix typo in PR template

base/servicehub/provider.go, base/servicehub/provider_context.go
/kind feature
Use label to distinguish multi provider instances.
=> servicehub provider context return label

go.mod, providers/component-protocol/provider.go, providers/component-protocol/provider_test.go
/kind feature
Add "X-Need-User-Indo" header to tell openapi to inject user info in response. Otherwise, openapi will skip injecting user info.
/assign @johnlanni
=> add X-Need-User-Info header in response

providers/component-protocol/protocol/component.go, providers/component-protocol/protocol/render.go, providers/component-protocol/protocol/render_test.go
/kind bug
adapt for structure `right` have list sub components.
```yaml
hierarchy:
......
structure:
leftHead:
right:
- leftHeadAddSceneSet
- moreOperation
left: leftHeadTitle
```
Fixes #
/assign @Effet
=> fix: cp default rendering recursive get sub comps

providers/component-protocol/cptype/operation.go, providers/component-protocol/utils/cputil/operation_builder.go
/kind feature
cp: operation add skipRender option, means this op is just a frontend op, won't invoke backend to render
/assign @Effet @shuofan
=> cp: operation add skipRender option

providers/component-protocol/cptype/component.go, providers/component-protocol/cptype/component_default.go
/kind refactor
cp: split IDefaultComponent from IComponent to clarify the development of std component's default impl.
/assign @Effet @shuofan
=> cp: split IDefaultComponent from IComponent

providers/component-protocol/cptype/operation.go, providers/component-protocol/utils/cputil/operation_builder.go
/kind bug
fix: cp opServerData do not wrap `extra` key.
before:
now: 
/assign @Effet
=> fix: cp opServerData do not wrap `extra` key

providers/component-protocol/cptype/protocol.go, providers/component-protocol/protocol/posthook/continue_render.go, providers/component-protocol/protocol/posthook/continue_render_test.go, providers/component-protocol/protocol/posthook/only_return_rendering.go, providers/component-protocol/protocol/posthook/only_return_rendering_test.go, providers/component-protocol/protocol/render.go
cp: 
- support component-level continue render
- render only return rendering components
[Erda Related Issue](https://erda.cloud/erda/dop/projects/387/issues/all?id=273374&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDA2LDQ0MDddfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=TASK)
/assign @Effet
=> feat: cp: support component-level continue render

providers/component-protocol/protocol/render.go
revert cp onlyReturnRendering temporarily
waiting UI
/assign @Effet
=> feat: revert cp onlyReturnRendering temporarily

providers/component-protocol/cpregister/register_comp.go, providers/component-protocol/examples/components/kanban_demo/kanban.http, providers/component-protocol/examples/components/kanban_demo/kanban/custom_type.go, providers/component-protocol/examples/components/kanban_demo/kanban/init.go, providers/component-protocol/examples/components/kanban_demo/kanban/provider.go, providers/component-protocol/examples/demo.yaml, providers/component-protocol/examples/i18n/scenarios/notbelong.yaml
decouple component's register from servicehub-provider
[Erda Issue](https://erda.cloud/erda/dop/projects/387/issues/all?id=275738&issueFilter__urlQuery=eyJ0aXRsZSI6Iue7hOS7tiIsInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=TASK)
/assign @Effet
=> feat: cp: component register decouple from servicehub-provider

providers/component-protocol/cpregister/base/comp_register.go, providers/component-protocol/cpregister/register_comp_provider.go, providers/component-protocol/examples/components/kanban_demo/kanban/init.go, providers/component-protocol/examples/demo.yaml, providers/component-protocol/utils/cputil/provider_name.go, providers/component-protocol/utils/cputil/provider_name_test.go
Sometimes, a component is a provider first, then become a component.
For this situation, we provide a more convenient method to use.
Previous:
Now:
/assign @Effet
=> feat: cp: optionally register component as provider

providers/component-protocol/protocol/render.go
cp: reopen onlyReturnRendering
erda-ui supported and cherry-picked to release/1.6 already.
/assign @Effet
=> cp: reopen onlyReturnRendering

providers/component-protocol/protocol/posthook/only_return_rendering.go, providers/component-protocol/protocol/render.go
fix: move ReturnAllComponents option check into func OnlyReturnRenderingComps
Fixes #
/assign @sfwn
=> fix: move ReturnAllComponents option check into func OnlyReturnRenderingComps

providers/component-protocol/protocol/posthook/simplify.go, providers/component-protocol/protocol/posthook/simplify_test.go, providers/component-protocol/protocol/render.go
cp: add simplify-protocol posthook, so both std and non-std comp can use it.
/assign @Effet
=> feat: cp add simplify-protocol posthook

base/servicehub/provider_context.go
logger use provider key as module name to distinguish multiple provider instances
/assign @recallsong 
before: 
now:
=> feat: logger use provider key as module name to distinguish multiple provider instances

providers/mysql/mysql.go, providers/mysqlxorm/xorm.go
enlarge mysql max open/idle connections.
currently, 1(idle)/2(max) is too small.
/assign @Effet @littlejiancc
=> chore: enlarge mysql max open/idle connections

.github/workflows/ci-it.yml
fix golangci-lint issue of go 1.18
Fixes #
/assign @Effet
=> fix: golangci-lint issue of go 1.18

tools/protoc/protoc-gen-go-form/form.go
feat: allows to skip go-form
I have a struct whose fields refer to itself. The `protoc-gen-go-form` plugin will stack overflow when dealing with such structures. However, it is not necessary to generate go-form code for each message. I wish to provide a way for developers to skip it: include the specific string `+skip_go-form` in the comment of the message.
我有一个 proto message, 它的字段引用了它本身. `protoc-gen-go-form` 在处理这样的结构时会栈溢出而失败. 然而每个 message 都生成 go-form 代码并不是必须的, 因此我想提供一个方法来跳过执行 go-form: 在 message 的头上添加 `+skip_go-form` 这样的注释。
```proto
// +SKIP_GO-FORM
message Schema {
string type = 5;
string title = 6;
string format = 7;
string description = 8;
bool deprecated = 20;
Schema items = 30;
repeated string required = 31;
map<string, Schema> properties = 32;
}
```
Fixes #
=> feat: allows to skip go-form

go.mod, go.sum, providers/all.go, providers/kafkav2/examples/producer/examples.yaml, providers/kafkav2/examples/producer/main.go, providers/kafkav2/kafka.go, providers/kafkav2/producer.go
support new kafka provider based on [kafka-go](https://github.com/segmentio/kafka-go) which is a pure go libarary
Fixes #
=> kafkav2 based on kafak-go

.github/PULL_REQUEST_TEMPLATE.md, providers/component-protocol/protocol/posthook/simplify.go, providers/component-protocol/protocol/posthook/simplify_test.go
Fix cp option visible can not be set to false.
https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTkwLDEyMTgsMTIyNF0sImFzc2lnbmVlIjpbIjEwMDEwNzMiXX0%3D&id=310462&iterationID=1190&pId=0&type=TASK
/assign @sfwn
=> fix: Fix cp option visible can not be set to false.

pkg/config/config.go, pkg/config/config_test.go
content config support env escape as file
/assign @snakorse
=> feat: hub content config support env escape as file

go.mod, providers/mysql/v2/mysql.go, providers/mysql/v2/option.go, providers/mysql/v2/plugins/fields/soft_delete.go, providers/mysql/v2/plugins/fields/soft_delete_stamp.go, providers/mysql/v2/plugins/fields/soft_delete_stamp_test.go, providers/mysql/v2/plugins/fields/soft_delete_test.go, providers/mysql/v2/tx.go, providers/mysql/v2/tx_test.go
- en:
- add field type `DeletedAtStamp` to support BIGINT type soft deleted field
- more APIs for gorm.v2 provider
- zh:
- 增加 `DeletedAtStamp` 字段类型以支持使用 BIGINT 类型作为软删除字段
- 为 gorm.v2 provider 添加更便捷的 APIs
```go
type User2 struct {
ID        uint
Name      string
Age       uint
DeletedAt fields.DeletedAtStamp
}
db.Model(&User2{}).Select("age").Where("name = ?", user.Name)
// SELECT `age` FROM `user2` WHERE name = "dspo" AND (`user2`.`deleted_at` = 0 OR `user2`.`deleted_at` IS NULL)
db.Delete(&user)
// UPDATE `user2` SET `deleted_at`=1656933047280 WHERE `user2`.`id` = 1 AND (`user2`.`deleted_at` = 0 OR `user2`.`deleted_at` IS NULL)
db.First(&User2{}, "name = ?", user.Name)
// SELECT * FROM `user2` WHERE name = "dspo" AND (`user2`.`deleted_at` = 0 OR `user2`.`deleted_at` IS NULL) ORDER BY …
```
=> feat: DeletedAtStamp; gorm.v2 provider

providers/httpserver/server/server.go
record http-server error to log
before:
after:
[Related Erda Issue](https://erda.cloud/erda/dop/projects/387/issues/all?id=325031&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1321&type=TASK)
=> feat: record http-server error to log

providers/httpserver/interceptors/interceptor.go, providers/httpserver/interceptors/interceptor_test.go, providers/httpserver/mock/httpresponsewriter.go, providers/httpserver/provider.go
httpserver add PassThroughDebugFlag middleware for proxy
=> feat: httpserver add PassThroughDebugFlag middleware for proxy

go.mod, tools/go.mod
specify required lowest go version is 1.17 in go.mod
=> specify required lowest go version is 1.17 in go.mod

providers/httpserver/provider.go
httpserver remove recover interceptor to avoid always statuscode 200
/assign @chengjoey
=> chore: httpserver remove recover interceptor to avoid always statuscode 200

pkg/trace/inject/hook/hook.go
func-hook judge `TRACE_HOOK_ENABLE` env
Fixes #
/assign @sfwn
=> fix: func-hook judge `TRACE_HOOK_ENABLE` env

tools/go.mod, tools/gohub/cmd/version/version.go
=> feat: update gohub version to 1.0.8

tools/protoc/protoc-gen-go-http/service.go
fix issue:
```
--go-http_out: service "ModelProviderService", method "Paging" : not support type "enum" for query string
```
Fixes #
=> feat: gohub protoc-gen-go-http service query string support enum type

providers/mysqlxorm/sqlite3/examples/examples.yaml, providers/mysqlxorm/sqlite3/examples/main.go, providers/mysqlxorm/sqlite3/interface.go, providers/mysqlxorm/sqlite3/interface_test.go, providers/mysqlxorm/sqlite3/provider.go, providers/mysqlxorm/xorm.go
add a sqlite3-xorm provider which implements the mysqlxorm
it can use to write for unit-test instead of `mock`
Fixes #
/assign @sfwn
=> add sqlite3-xorm provider

providers/mysqlxorm/sqlite3/examples/examples.yaml, providers/mysqlxorm/sqlite3/examples/main.go, providers/mysqlxorm/sqlite3/interface.go, providers/mysqlxorm/sqlite3/interface_test.go, providers/mysqlxorm/sqlite3/options.go, providers/mysqlxorm/sqlite3/provider.go, providers/mysqlxorm/xorm.go
To add the DataSourceName and Close methods for xorm, and support SQLite3's random filename,
Fixes #
/assign @sfwn
=> feat: add xorm closeState and sqlite's randomName

.github/workflows/ci-it.yml, providers/etcd/etcd.go
support all etcd client configs
/assign @sfwn
=> feat: support all etcd client configs

base/logs/logrusx/log.go, base/logs/logs.go
Logger support set multiple KVs for more log details.
=> feat(logger): support Set KV multiple times as entry fields
